---
- name: Show how to loop through a set of groups
  hosts: cluster_group_?
  gather_facts: false
  become: false
  tasks:
    - name: The loop happens for each host, might be too much
      ansible.builtin.debug:
        msg: do something with {{ item }}
      loop: "{{ groups[cluster_group_name] }}"

    - name: The loop happens only for the first host in each group
      ansible.builtin.debug:
        msg: do something with {{ item }}
      loop: "{{ groups[cluster_group_name] }}"
      when: inventory_hostname == groups[cluster_group_name][0]

    - name: Make the first host of each group fail to simulate non-availability
      ansible.builtin.assert:
        that: inventory_hostname != groups[cluster_group_name][0]

    - name: The loop happens only for the first _available_ host in each group
      ansible.builtin.debug:
        msg: do something with {{ item }}
      loop: "{{ groups[cluster_group_name] }}"
      when: >-
        inventory_hostname == (groups[cluster_group_name]
        | intersect(ansible_play_hosts))[0]
