- name: A playbook can be a list of roles included with tags
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Include role1
      ansible.builtin.include_role:
        name: role1
        apply:
          tags: [role1, deploy]
      tags:
        - role1
        - deploy

    - name: Include role2
      ansible.builtin.include_role:
        name: role2
        apply:
          tags: [role2, deploy, configure]
      tags:
        - role2
        - deploy
        - configure

    - name: Include role3
      ansible.builtin.include_role:
        name: role3
        apply:
          tags: [role3, configure]
      tags:
        - role3
        - configure
