- name: A playbook can be a list of roles imported with tags
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Import role1
      ansible.builtin.import_role:
        name: role1
      tags:
        - role1
        - deploy
    - name: Import role2
      ansible.builtin.import_role:
        name: role2
      tags:
        - role2
        - deploy
        - configure
    - name: Import role3
      ansible.builtin.import_role:
        name: role3
      tags:
        - role3
        - configure
