---
# tasks file for prefix_show
- name: Show where we are
  ansible.builtin.debug:
    msg: we're now in the main task file
- name: Include the sub task file without prefix
  ansible.builtin.include_tasks:
    file: sub_noprefix.yml
- name: Include the sub task file with prefix
  ansible.builtin.include_tasks:
    file: sub_prefix.yml
- name: Show where we are
  ansible.builtin.debug:
    msg: we're back in the main task file
