- name: Provision hosts in a bad way
  hosts: managers
  gather_facts: false
  become: false
  tasks:
    - name: Create some file to simulate an API call to provision a host
      ansible.builtin.copy:
        content: "{{ item.provision_value }}\n"
        dest: "/tmp/bad_{{ inventory_hostname }}_{{ item.name }}.txt"
        force: true
        owner: root
        group: root
        mode: "0644"
      loop: "{{ provision_list_of_hosts }}"
